services:
  get_data:
    build:
      context: .
    env_file:
      - .env
    entrypoint: ./get_data.sh
    depends_on:
      - db
    networks:
      - population_app_network

  print_data:
    build:
      context: .
    env_file:
      - .env
    entrypoint: ./print_data.sh
    depends_on:
      - db
    networks:
      - population_app_network

  db:
    image: postgres:17.0-alpine3.20
    container_name: population_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - population_app_network


networks:
  population_app_network:
    driver: bridge

volumes:
  postgres_data: {}