"""Add population table for statistics times

Revision ID: 199b6303720e
Revises: b939a544946c
Create Date: 2025-03-01 19:53:49.522528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '199b6303720e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('population_stats_times',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('population_2023', sa.BigInteger(), nullable=True),
    sa.Column('population_2024', sa.BigInteger(), nullable=True),
    sa.Column('change', sa.BigInteger(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('population_stats_times')
    # ### end Alembic commands ###
