"""Add population table for wiki

Revision ID: b939a544946c
Revises: 
Create Date: 2025-03-01 17:53:11.825179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b939a544946c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('population_wiki',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('population_2022', sa.BigInteger(), nullable=True),
    sa.Column('population_2023', sa.BigInteger(), nullable=True),
    sa.Column('change', sa.Float(), nullable=True),
    sa.Column('continental_region', sa.String(), nullable=True),
    sa.Column('statistical_region', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('population_wiki')
    # ### end Alembic commands ###
